/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    categories: Category;
    products: Product;
    product_variations: ProductVariation;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    product_variations: ProductVariationsSelect<false> | ProductVariationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  /**
   * Unique category identifier (e.g. cat-apparel, cat-outerwear)
   */
  id: string;
  /**
   * Category name (e.g. Original Sculptures, Fine Art Prints)
   */
  name: string;
  /**
   * URL-friendly category slug for filtering and navigation
   */
  slug: string;
  /**
   * Parent category for hierarchical nesting (supports depth-2 category navigation)
   */
  parent?: (string | null) | Category;
  /**
   * Editorial description of the adventure gear category
   */
  description?: string | null;
  /**
   * Hero cover image for the category
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descriptive alt text for accessibility and SEO (WCAG 2.1 AA compliance)
   */
  alt: string;
  /**
   * Optional visible caption displayed beneath the image in galleries
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  /**
   * Unique product identifier (e.g. prod-bushwhack-anorak)
   */
  id: string;
  /**
   * Product or artwork title
   */
  title: string;
  /**
   * URL-friendly product slug for storefront page routing
   */
  slug: string;
  /**
   * Linked Shopify Product GID (e.g. gid://shopify/Product/1234567890)
   */
  shopify_product_id?: string | null;
  /**
   * Base price in USD. Synchronized to default Shopify variant.
   */
  base_price: number;
  /**
   * Lifecycle state of the artwork
   */
  status: 'draft' | 'scheduled' | 'active' | 'archived';
  /**
   * Primary product category taxonomy reference
   */
  category_id?: (string | null) | Category;
  /**
   * Primary hero image for catalog grids and detail pages
   */
  featured_image?: (number | null) | Media;
  /**
   * Supporting high-resolution artwork photographs and angle shots
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Chris’s bench and field notes on design, construction, and bank-testing conditions
   */
  maker_field_notes?: string | null;
  /**
   * Legacy artist statement field (mapped to maker_field_notes)
   */
  artist_statement?: string | null;
  /**
   * Technical fabric specs and hardware (e.g. 3-Layer DWR Ripstop, 500D Cordura®, YKK AquaGuard®)
   */
  materials?: string | null;
  /**
   * Total garment/pack weight (e.g. 21.4 oz / 606g)
   */
  weight?: string | null;
  /**
   * Fit characteristics (e.g. Relaxed Athletic with articulated elbows)
   */
  fit_profile?: string | null;
  /**
   * Workshop production provenance
   */
  origin?: string | null;
  /**
   * Full rich text editorial description rendered via Lexical editor
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product_variations".
 */
export interface ProductVariation {
  /**
   * Unique variation identifier (e.g. var-anorak-olive)
   */
  id: string;
  /**
   * Parent product for this variation or edition
   */
  product_id: string | Product;
  /**
   * Linked Shopify ProductVariant GID (e.g. gid://shopify/ProductVariant/987654321)
   */
  shopify_variant_id?: string | null;
  /**
   * Edition or variation title (e.g. Obsidian Cast Edition, Giclée Print 24x36)
   */
  variation_name: string;
  /**
   * Unique Stock Keeping Unit (SKU) identifier
   */
  sku: string;
  /**
   * Maker batch classification (Standard run vs workshop micro-batch)
   */
  variation_type?: ('standard' | 'micro_batch' | 'one_of_one' | 'prototype') | null;
  /**
   * Prominent badge tag for limited runs (e.g. "Only 3 Crafted", "Deadstock Duck Camo Edition")
   */
  edition_badge?: string | null;
  /**
   * Maker story for this variation (deadstock fabric provenance, sewing table notes, differences from standard silhouette)
   */
  variation_notes?: string | null;
  /**
   * Quick workbench detail photos specific to this variation. Automatically prepended to the parent gallery on the PDP.
   */
  variation_images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional price override. When omitted, falls back to parent product base_price.
   */
  price_override?: number | null;
  /**
   * Indicates whether this variation is a capped, numbered limited edition run
   */
  is_limited_edition?: boolean | null;
  /**
   * Total serialized prints/casts manufactured in this edition run
   */
  total_edition_count?: number | null;
  /**
   * Scheduled drop timestamp to drive storefront countdown timers
   */
  release_date?: string | null;
  /**
   * Editorial availability status. Note: live checkout inventory availability is validated against Shopify.
   */
  status: 'coming_soon' | 'active' | 'sold_out' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'product_variations';
        value: string | ProductVariation;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  slug?: T;
  parent?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  id?: T;
  title?: T;
  slug?: T;
  shopify_product_id?: T;
  base_price?: T;
  status?: T;
  category_id?: T;
  featured_image?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  maker_field_notes?: T;
  artist_statement?: T;
  materials?: T;
  weight?: T;
  fit_profile?: T;
  origin?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product_variations_select".
 */
export interface ProductVariationsSelect<T extends boolean = true> {
  id?: T;
  product_id?: T;
  shopify_variant_id?: T;
  variation_name?: T;
  sku?: T;
  variation_type?: T;
  edition_badge?: T;
  variation_notes?: T;
  variation_images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  price_override?: T;
  is_limited_edition?: T;
  total_edition_count?: T;
  release_date?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}