/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    categories: Category;
    product_lines: ProductLine;
    products: Product;
    product_variations: ProductVariation;
    media: Media;
    users: User;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    product_lines: ProductLinesSelect<false> | ProductLinesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    product_variations: ProductVariationsSelect<false> | ProductVariationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    themeSettings: ThemeSetting;
  };
  globalsSelect: {
    themeSettings: ThemeSettingsSelect<false> | ThemeSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  /**
   * Unique category identifier (e.g. cat-apparel, cat-outerwear)
   */
  id: string;
  /**
   * Category name (e.g. Original Sculptures, Fine Art Prints)
   */
  name: string;
  /**
   * URL-friendly category slug for filtering and navigation
   */
  slug: string;
  /**
   * Parent category for hierarchical nesting (supports depth-2 category navigation)
   */
  parent?: (string | null) | Category;
  /**
   * Editorial description of the adventure gear category
   */
  description?: string | null;
  /**
   * Hero cover image for the category
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descriptive alt text for accessibility and SEO (WCAG 2.1 AA compliance)
   */
  alt: string;
  /**
   * Optional visible caption displayed beneath the media item in galleries
   */
  caption?: string | null;
  /**
   * Discriminator for rendering still photography, HTML5 video, or animated GIFs.
   */
  media_type?: ('image' | 'video' | 'gif') | null;
  /**
   * Poster frame image shown before video playback or on low-bandwidth connections.
   */
  poster?: (number | null) | Media;
  /**
   * Direct URL or path to fallback poster frame image.
   */
  poster_url?: string | null;
  /**
   * Continuously loop video playback.
   */
  loop?: boolean | null;
  /**
   * Automatically play muted video when entering viewport.
   */
  auto_play?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product_lines".
 */
export interface ProductLine {
  /**
   * Unique product line identifier (e.g. line-alpine-chest-rig)
   */
  id: string;
  /**
   * Narrative line or capsule title (e.g. Alpine Chest Rig System)
   */
  title: string;
  /**
   * URL-friendly slug for capsule lookbooks and series landing pages
   */
  slug: string;
  /**
   * Shared narrative story, design philosophy, and field testing background
   */
  story?: string | null;
  /**
   * Optional default base price in USD. Inherited by child products that do not specify an override price.
   */
  default_price?: number | null;
  /**
   * Capsule hero banner image
   */
  hero_image?: (number | null) | Media;
  /**
   * Atmospheric field lookbook photography for the entire product line
   */
  lookbook_gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  /**
   * Unique product identifier (e.g. prod-rig-minimalist)
   */
  id: string;
  /**
   * Product title
   */
  title: string;
  /**
   * URL-friendly slug for storefront product detail page routing
   */
  slug: string;
  /**
   * Direct 1:1 linked Shopify Product GID
   */
  shopify_product_id?: string | null;
  /**
   * Base price in USD. If product line is specified, can be inherited from line default.
   */
  base_price: number;
  /**
   * Optional price override. If omitted, falls back to base_price or line default_price.
   */
  price?: number | null;
  /**
   * Unique Stock Keeping Unit (SKU)
   */
  sku?: string | null;
  /**
   * Optional parent product line or drop capsule for shared narrative & default price inheritance
   */
  product_line_id?: (string | null) | ProductLine;
  /**
   * Legacy category relationship for backward compatibility
   */
  category_id?: (string | null) | Category;
  /**
   * Controlled category dropdown (fast authoring directly on product record)
   */
  category?: ('apparel' | 'packs' | 'accessories') | null;
  /**
   * Colorways, sizing, or material editions available for this product
   */
  options?:
    | {
        name: string;
        value: string;
        sku_suffix?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Lifecycle state of the product
   */
  status: 'draft' | 'scheduled' | 'active' | 'archived';
  /**
   * Primary hero image for catalog grids and detail pages
   */
  featured_image?: (number | null) | Media;
  /**
   * Supporting workbench and field photographs
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Chris's bench and field testing notes
   */
  maker_field_notes?: string | null;
  /**
   * Standard BankBeaters technical textile preset. Auto-populates Materials field when left blank.
   */
  material_preset?:
    | (
        | 'toray_cordura'
        | 'stretch_cordura'
        | 'xpac_vx21'
        | 'cordura_eva'
        | 'martexin_blaze'
        | 'waxed_eva'
        | 'dyneema_composite'
        | 'custom'
      )
    | null;
  /**
   * Technical fabric specs and hardware. Auto-filled from Material Preset or customizable.
   */
  materials?: string | null;
  /**
   * Garment or pack weight (e.g. 21.4 oz (606g))
   */
  weight?: string | null;
  /**
   * Controlled fit characteristics or carrying ergonomics preset
   */
  fit_profile?:
    | (
        | 'Technical Straight (Articulated knees, gusseted seat for steep cut-bank scrambles)'
        | 'Relaxed Athletic (Engineered for layering and overhead casting mobility)'
        | 'Low-Profile 4-Point Harness (Rides high above deep wading lines)'
        | 'Ambidextrous Sling / Lumbar Switchable with Breathable 3D Spacer Mesh'
        | 'Tri-Fold Compact (Fits into any thigh pocket or pack exterior sleeve)'
        | 'Low Crown 5-Panel with Nylon Webbing Quick-Release Adjuster'
        | 'Standard True-to-Size Workshop Spec'
        | 'Custom Spec / Workbench Fit'
      )
    | null;
  /**
   * Workshop production provenance
   */
  origin?: string | null;
  /**
   * Full editorial description
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product_variations".
 */
export interface ProductVariation {
  /**
   * Unique variation identifier (e.g. var-anorak-olive)
   */
  id: string;
  /**
   * Parent product for this variation or edition
   */
  product_id: string | Product;
  /**
   * Linked Shopify ProductVariant GID (e.g. gid://shopify/ProductVariant/987654321)
   */
  shopify_variant_id?: string | null;
  /**
   * Edition or variation title (e.g. Obsidian Cast Edition, Giclée Print 24x36)
   */
  variation_name: string;
  /**
   * Unique Stock Keeping Unit (SKU) identifier
   */
  sku: string;
  /**
   * Maker batch classification (Standard run vs workshop micro-batch)
   */
  variation_type?: ('standard' | 'micro_batch' | 'one_of_one' | 'prototype') | null;
  /**
   * Prominent badge tag for limited runs (e.g. "Only 3 Crafted", "Deadstock Duck Camo Edition")
   */
  edition_badge?: string | null;
  /**
   * Maker story for this variation (deadstock fabric provenance, sewing table notes, differences from standard silhouette)
   */
  variation_notes?: string | null;
  /**
   * Quick workbench detail photos specific to this variation. Automatically prepended to the parent gallery on the PDP.
   */
  variation_images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional price override. When omitted, falls back to parent product base_price.
   */
  price_override?: number | null;
  /**
   * Indicates whether this variation is a capped, numbered limited edition run
   */
  is_limited_edition?: boolean | null;
  /**
   * Total serialized prints/casts manufactured in this edition run
   */
  total_edition_count?: number | null;
  /**
   * Scheduled drop timestamp to drive storefront countdown timers
   */
  release_date?: string | null;
  /**
   * Editorial availability status. Note: live checkout inventory availability is validated against Shopify.
   */
  status: 'coming_soon' | 'active' | 'sold_out' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Internal page title (e.g. "Homepage", "About The Maker", "Spring 2026 Drop").
   */
  title: string;
  /**
   * URL slug (e.g. "homepage", "about", "drops").
   */
  slug: string;
  status?: ('draft' | 'published') | null;
  /**
   * Drag and drop blocks to customize the layout and section order of this page.
   */
  layout: (
    | {
        /**
         * Choose hero composition: full-bleed photographic overlay, split workshop editorial, or direct catalog header.
         */
        layoutPreset: 'minimalist_overlay' | 'field_workshop' | 'catalog_direct';
        /**
         * Primary hero headline.
         */
        headline: string;
        /**
         * Top tracking eyebrow or subheadline.
         */
        subheadline?: string | null;
        /**
         * Core ethos or craft statement.
         */
        ethosStatement?: string | null;
        /**
         * Path or URL to high-resolution photographic background (Cloudflare R2).
         */
        backdropImage?: string | null;
        /**
         * Optional Payload Media asset reference for backdrop.
         */
        backdropMedia?: (number | null) | Media;
        /**
         * Prominent badge label.
         */
        badgeText?: string | null;
        /**
         * Craftsmanship provenance callout footer.
         */
        provenanceCallout?: string | null;
        ctaButtons?:
          | {
              label: string;
              href: string;
              variant?: ('primary' | 'outline' | 'ghost') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        title: string;
        subtitle?: string | null;
        /**
         * Scheduled release timestamp for countdown timer.
         */
        targetDate?: string | null;
        ctaText?: string | null;
        ctaHref?: string | null;
        teaserNotes?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'dropCountdown';
      }
    | {
        title: string;
        subtitle?: string | null;
        categoryFilter?: ('all' | 'outerwear' | 'packs-carry' | 'field-accessories') | null;
        /**
         * Maximum number of items to display.
         */
        limit?: number | null;
        /**
         * Display "Starting at $X.XX" badge.
         */
        showStartingPrice?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'featuredCollection';
      }
    | {
        eyebrow?: string | null;
        headline: string;
        storyText?: string | null;
        pillars?:
          | {
              icon?: string | null;
              title: string;
              description: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'craftsmanshipStory';
      }
    | {
        eyebrow?: string | null;
        headline: string;
        materials?:
          | {
              name: string;
              spec: string;
              badge?: string | null;
              description: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'materialProvenance';
      }
  )[];
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'product_lines';
        value: string | ProductLine;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'product_variations';
        value: string | ProductVariation;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  slug?: T;
  parent?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product_lines_select".
 */
export interface ProductLinesSelect<T extends boolean = true> {
  id?: T;
  title?: T;
  slug?: T;
  story?: T;
  default_price?: T;
  hero_image?: T;
  lookbook_gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  id?: T;
  title?: T;
  slug?: T;
  shopify_product_id?: T;
  base_price?: T;
  price?: T;
  sku?: T;
  product_line_id?: T;
  category_id?: T;
  category?: T;
  options?:
    | T
    | {
        name?: T;
        value?: T;
        sku_suffix?: T;
        id?: T;
      };
  status?: T;
  featured_image?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  maker_field_notes?: T;
  material_preset?: T;
  materials?: T;
  weight?: T;
  fit_profile?: T;
  origin?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product_variations_select".
 */
export interface ProductVariationsSelect<T extends boolean = true> {
  id?: T;
  product_id?: T;
  shopify_variant_id?: T;
  variation_name?: T;
  sku?: T;
  variation_type?: T;
  edition_badge?: T;
  variation_notes?: T;
  variation_images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  price_override?: T;
  is_limited_edition?: T;
  total_edition_count?: T;
  release_date?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  media_type?: T;
  poster?: T;
  poster_url?: T;
  loop?: T;
  auto_play?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              layoutPreset?: T;
              headline?: T;
              subheadline?: T;
              ethosStatement?: T;
              backdropImage?: T;
              backdropMedia?: T;
              badgeText?: T;
              provenanceCallout?: T;
              ctaButtons?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        dropCountdown?:
          | T
          | {
              title?: T;
              subtitle?: T;
              targetDate?: T;
              ctaText?: T;
              ctaHref?: T;
              teaserNotes?: T;
              id?: T;
              blockName?: T;
            };
        featuredCollection?:
          | T
          | {
              title?: T;
              subtitle?: T;
              categoryFilter?: T;
              limit?: T;
              showStartingPrice?: T;
              id?: T;
              blockName?: T;
            };
        craftsmanshipStory?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              storyText?: T;
              pillars?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        materialProvenance?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              materials?:
                | T
                | {
                    name?: T;
                    spec?: T;
                    badge?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themeSettings".
 */
export interface ThemeSetting {
  id: number;
  /**
   * Choose typography pairings for display headlines and body text.
   */
  fontPreset: 'shippori_jakarta' | 'space_plex' | 'fraunces_inter';
  /**
   * Primary storefront canvas background color.
   */
  surfaceCanvas: '#0F1215' | '#0B0E11' | '#15191E';
  /**
   * Brand accent color (default: Signal Hazard Orange #E55B24).
   */
  accentColor: string;
  /**
   * Border contrast intensity across cards and section dividers.
   */
  hairlineBorder?: ('subtle' | 'defined' | 'blaze') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themeSettings_select".
 */
export interface ThemeSettingsSelect<T extends boolean = true> {
  fontPreset?: T;
  surfaceCanvas?: T;
  accentColor?: T;
  hairlineBorder?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}